<?php 


$oldPermissions = [
            "user_view",
            "user_add",
            "user_edit",
            "user_delete",
            "role_view",
            "role_add",
            "role_edit",
            "role_delete",
            "supplier_all",
            "supplier_add",
            "supplier_import",
            "supplier_edit",
            "supplier_delete",
            "customer_all",
            "customer_add",
            "customer_import",
            "customer_edit",
            "customer_delete",
            "customer_group",
            "customer_report",
            "supplier_report",
            "product_all",
            "product_add",
            "product_edit",
            "openingStock_add",
            "product_delete",
            "categories",
            "brand",
            "units",
            "variant",
            "warranties",
            "selling_price_group",
            "generate_barcode",
            "product_settings",
            "stock_report",
            "stock_in_out_report",
            "purchase_all",
            "purchase_add",
            "purchase_edit",
            "purchase_delete",
            // "purchase_payment",
            "purchase_payment_index",
            "purchase_return",
            "status_update",
            "purchase_settings",
            "purchase_statements",
            "purchase_sale_report",
            "pro_purchase_report",
            "purchase_payment_report",
            "adjustment_all",
            "adjustment_add_from_location",
            "adjustment_add_from_warehouse",
            "adjustment_delete",
            "stock_adjustment_report",
            "view_expense",
            "add_expense",
            "edit_expense",
            "delete_expense",
            "expense_category",
            "category_wise_expense",
            "expanse_report",
            "create_add_sale",
            "view_sales",
            "edit_sale",
            "delete_sale",
            "sale_settings",
            "sale_draft",
            "add_quotation",
            "sale_quotation_list",
            "sale_quotation_edit",
            "sale_quotation_delete",
            "sale_order_add",
            "sale_order_all",
            "sale_order_edit",
            "sale_order_do_approval",
            "sale_order_delete",
            "do_add",
            "do_all",
            "do_edit",
            "do_delete",
            "change_expire_date",
            "do_to_final",
            "quotation_notification",
            "sales_order_notification",
            "do_notification",
            "do_approval_notification",
            // "sale_payment",
            "receive_payment_index",
            "edit_price_sale_screen",
            "edit_discount_sale_screen",
            "shipment_access",
            "view_product_cost_is_sale_screed",
            "view_own_sale",
            "discounts",
            "pos_all",
            "pos_add",
            "pos_edit",
            "pos_delete",
            "edit_price_pos_screen",
            "edit_discount_pos_screen",
            "pos_sale_settings",
            "view_sales_return",
            "add_sales_return",
            "edit_sales_return",
            "delete_sales_return",
            "sale_statements",
            "sale_return_statements",
            "pro_sale_report",
            "sale_payment_report",
            "c_register_report",
            "sale_representative_report",
            "register_view",
            "register_close",
            "another_register_close",
            "loss_profit_report",
            "tax_report",
            "payroll_report",
            "payroll_payment_report",
            "attendance_report",
            "production_report",
            "financial_report",
            "g_settings",
            "p_settings",
            "barcode_settings",
            "about_all",
            "reset",
            "tax",
            "branch",
            "warehouse",
            "inv_sc",
            "inv_lay",
            "cash_counters",
            "dash_data",
            "ac_access",
            "hrm_dashboard",
            "leave_type",
            "leave_assign",
            "shift",
            "attendance",
            "view_allowance_and_deduction",
            "payroll",
            "holiday",
            "department",
            "designation",
            "assign_todo",
            "work_space",
            "memo",
            "msg",
            "process_view",
            "process_add",
            "process_edit",
            "process_delete",
            "production_view",
            "production_add",
            "production_edit",
            "production_delete",
            "manuf_settings",
            "process_report",
            "manuf_report",
            "proj_view",
            "proj_create",
            "proj_edit",
            "proj_delete",
            "ripe_add_invo",
            "ripe_edit_invo",
            "ripe_view_invo",
            "ripe_delete_invo",
            "change_invo_status",
            "ripe_jop_sheet_status",
            "ripe_jop_sheet_add",
            "ripe_jop_sheet_edit",
            "ripe_jop_sheet_delete",
            "ripe_only_assinged_job_sheet",
            "ripe_view_all_job_sheet",
            "superadmin_access_pack_subscrip",
            "e_com_sync_pro_cate",
            "e_com_sync_pro",
            "e_com_sync_order",
            "e_com_map_tax_rate",
            "today_summery",
            "communication",
            "create_requisition",
            "all_requisition",
            "edit_requisition",
            "approve_requisition",
            "delete_requisition",
            "create_po",
            "all_po",
            "edit_po",
            "delete_po",
            "requisition_notification",
            "po_notification",
            "view_purchase_return",
            "add_purchase_return",
            "edit_purchase_return",
            "delete_purchase_return",
            "transfer_wh_to_bl",
            "transfer_bl_wh",
            "transfer_bl_bl",
            "banks",
            "accounts",
            "assets",
            "loans",
            "contra",
            "balance_sheet",
            "trial_balance",
            "cash_flow",
            "profit_loss_ac",
            "daily_profit_loss",
            "notice_board",
            "email",
            "email_settings",
            "sms",
            "sms_settings",
            "media",
            "calender",
            "announcement",
            "activity_log",
            "database_backup",
            // Asset Module
            "asset_settings",
            "asset_index",
            "asset_create",
            "asset_view",
            "asset_update",
            "asset_delete",
            "asset_components_index",
            "asset_components_create",
            "asset_components_view",
            "asset_components_update",
            "asset_components_delete",
            "asset_allocation_index",
            "asset_allocation_create",
            "asset_allocation_view",
            "asset_allocation_update",
            "asset_allocation_delete",
            "asset_depreciation_index",
            "asset_depreciation_create",
            "asset_depreciation_view",
            "asset_depreciation_update",
            "asset_depreciation_delete",
            "asset_licenses_index",
            "asset_licenses_create",
            "asset_licenses_view",
            "asset_licenses_update",
            "asset_licenses_delete",
            "asset_manufacturer_index",
            "asset_manufacturer_create",
            "asset_manufacturer_view",
            "asset_manufacturer_update",
            "asset_manufacturer_delete",
            "asset_categories_index",
            "asset_categories_create",
            "asset_categories_view",
            "asset_categories_update",
            "asset_categories_delete",
            "asset_locations_index",
            "asset_locations_create",
            "asset_locations_view",
            "asset_locations_update",
            "asset_locations_delete",
            "asset_units_index",
            "asset_units_create",
            "asset_units_view",
            "asset_units_update",
            "asset_units_delete",
            "asset_requests_index",
            "asset_requests_create",
            "asset_requests_view",
            "asset_requests_update",
            "asset_requests_delete",
            "asset_warranties_index",
            "asset_warranties_create",
            "asset_warranties_view",
            "asset_warranties_update",
            "asset_warranties_delete",
            "asset_audits_index",
            "asset_audits_create",
            "asset_audits_view",
            "asset_audits_update",
            "asset_audits_delete",
            "asset_revokes_index",
            "asset_revokes_create",
            "asset_revokes_view",
            "asset_revokes_update",
            "asset_revokes_delete",
            "asset_terms_and_conditions_index",
            "asset_terms_and_conditions_create",
            "asset_terms_and_conditions_view",
            "asset_terms_and_conditions_update",
            "asset_terms_and_conditions_delete",
            "asset_term_condition_categories_index",
            "asset_term_condition_categories_create",
            "asset_term_condition_categories_view",
            "asset_term_condition_categories_update",
            "asset_term_condition_categories_delete",
            "print_invoice",
            "print_challan",
            "print_weight",
            // Stock Issue
            "stock_issue",
            "stock_issue_index",
            "stock_issue_create",
            "stock_issue_view",
            "stock_issue_update",
            "stock_issue_delete",
            // Daily Stock
            "daily_stock",
            "daily_stock_index",
            "daily_stock_create",
            "daily_stock_view",
            "daily_stock_update",
            "daily_stock_delete",

            // Daily stock report
            "daily_stock_report",
            "stock_out_report",

            "opening_lc",
            "opening_lc_index",
            "opening_lc_create",
            "opening_lc_view",
            "opening_lc_update",
            "opening_lc_delete",

            "import_purchase_order",
            "import_purchase_order_index",
            "import_purchase_order_create",
            "import_purchase_order_view",
            "import_purchase_order_update",
            "import_purchase_order_delete",

            "exporters",
            "exporters_index",
            "exporters_create",
            "exporters_view",
            "exporters_update",
            "exporters_delete",

            "insurance_companies",
            "insurance_companies_index",
            "insurance_companies_create",
            "insurance_companies_view",
            "insurance_companies_update",
            "insurance_companies_delete",

            "cnf_agents",
            "cnf_agents_index",
            "cnf_agents_create",
            "cnf_agents_view",
            "cnf_agents_update",
            "cnf_agents_delete",

            "sales_order_report",
            "ordered_item_report",
            "do_vs_sales_report",

            "add_new_recent_price",
            "all_previous_recent_price",
            "today_recent_price",
            "price_update_notification",

            // "receive_payment_index", -> look at above, it replaced in place of `sale_payment`. Order kept for database consistency from production DB
            "receive_payment_create",
            "receive_payment_view",
            "receive_payment_update",
            "receive_payment_delete",

            // "purchase_payment_index", -> look at above its replaced in place of purchase_payment. Kept its old position for database backward-compatibility
            "purchase_payment_create",
            "purchase_payment_view",
            "purchase_payment_update",
            "purchase_payment_delete",

            "customer_manage",
            "customer_payment_receive_voucher",
            "customer_status_change",

            "whatsapp_messages_index",
            "whatsapp_messages_create",
            "whatsapp_messages_view",

            "whatsapp_messages_update",
            "whatsapp_messages_delete",

            "change_log_index",
            "change_log_create",
            "change_log_view",
            "change_log_update",
            "change_log_delete",

            "asset_licenses_categories_index",
            "asset_licenses_categories_create",
            "asset_licenses_categories_view",
            "asset_licenses_categories_update",
            "asset_licenses_categories_delete",

            "feedback_index",

        ];

$permissions = [
0 => "about_all",
1 => "ac_access",
2 => "accounts",
3 => "activity_log",
4 => "add_expense",
5 => "add_new_recent_price",
6 => "add_purchase_return",
7 => "add_quotation",
8 => "add_sales_return",
9 => "adjustment_add_from_location",
10 => "adjustment_add_from_warehouse",
11 => "adjustment_all",
12 => "adjustment_delete",
13 => "all_po",
14 => "all_previous_recent_price",
15 => "all_requisition",
16 => "announcement",
17 => "another_register_close",
18 => "approve_requisition",
19 => "asset_allocation_create",
20 => "asset_allocation_delete",
21 => "asset_allocation_index",
22 => "asset_allocation_update",
23 => "asset_allocation_view",
24 => "asset_audits_create",
25 => "asset_audits_delete",
26 => "asset_audits_index",
27 => "asset_audits_update",
28 => "asset_audits_view",
29 => "asset_categories_create",
30 => "asset_categories_delete",
31 => "asset_categories_index",
32 => "asset_categories_update",
33 => "asset_categories_view",
34 => "asset_components_create",
35 => "asset_components_delete",
36 => "asset_components_index",
37 => "asset_components_update",
38 => "asset_components_view",
39 => "asset_create",
40 => "asset_delete",
41 => "asset_depreciation_create",
42 => "asset_depreciation_delete",
43 => "asset_depreciation_index",
44 => "asset_depreciation_update",
45 => "asset_depreciation_view",
46 => "asset_index",
47 => "asset_licenses_categories_create",
48 => "asset_licenses_categories_delete",
49 => "asset_licenses_categories_index",
50 => "asset_licenses_categories_update",
51 => "asset_licenses_categories_view",
52 => "asset_licenses_create",
53 => "asset_licenses_delete",
54 => "asset_licenses_index",
55 => "asset_licenses_update",
56 => "asset_licenses_view",
57 => "asset_locations_create",
58 => "asset_locations_delete",
59 => "asset_locations_index",
60 => "asset_locations_update",
61 => "asset_locations_view",
62 => "asset_manufacturer_create",
63 => "asset_manufacturer_delete",
64 => "asset_manufacturer_index",
65 => "asset_manufacturer_update",
66 => "asset_manufacturer_view",
67 => "asset_requests_create",
68 => "asset_requests_delete",
69 => "asset_requests_index",
70 => "asset_requests_update",
71 => "asset_requests_view",
72 => "asset_revokes_create",
73 => "asset_revokes_delete",
74 => "asset_revokes_index",
75 => "asset_revokes_update",
76 => "asset_revokes_view",
77 => "asset_settings",
78 => "asset_term_condition_categories_create",
79 => "asset_term_condition_categories_delete",
80 => "asset_term_condition_categories_index",
81 => "asset_term_condition_categories_update",
82 => "asset_term_condition_categories_view",
83 => "asset_terms_and_conditions_create",
84 => "asset_terms_and_conditions_delete",
85 => "asset_terms_and_conditions_index",
86 => "asset_terms_and_conditions_update",
87 => "asset_terms_and_conditions_view",
88 => "asset_units_create",
89 => "asset_units_delete",
90 => "asset_units_index",
91 => "asset_units_update",
92 => "asset_units_view",
93 => "asset_update",
94 => "asset_view",
95 => "asset_warranties_create",
96 => "asset_warranties_delete",
97 => "asset_warranties_index",
98 => "asset_warranties_update",
99 => "asset_warranties_view",
100 => "assets",
101 => "assign_todo",
102 => "attendance",
103 => "attendance_report",
104 => "balance_sheet",
105 => "banks",
106 => "barcode_settings",
107 => "branch",
108 => "brand",
109 => "c_register_report",
110 => "calender",
111 => "cash_counters",
112 => "cash_flow",
113 => "categories",
114 => "category_wise_expense",
115 => "change_expire_date",
116 => "change_invo_status",
117 => "cnf_agents",
118 => "cnf_agents_create",
119 => "cnf_agents_delete",
120 => "cnf_agents_index",
121 => "cnf_agents_update",
122 => "cnf_agents_view",
123 => "communication",
124 => "contra",
125 => "create_add_sale",
126 => "create_po",
127 => "create_requisition",
128 => "customer_add",
129 => "customer_all",
130 => "customer_delete",
131 => "customer_edit",
132 => "customer_group",
133 => "customer_import",
134 => "customer_manage",
135 => "customer_payment_receive_voucher",
136 => "customer_report",
137 => "customer_status_change",
138 => "daily_profit_loss",
139 => "daily_stock",
140 => "daily_stock_create",
141 => "daily_stock_delete",
142 => "daily_stock_index",
143 => "daily_stock_report",
144 => "daily_stock_update",
145 => "daily_stock_view",
146 => "dash_data",
147 => "database_backup",
148 => "delete_expense",
149 => "delete_po",
150 => "delete_purchase_return",
151 => "delete_requisition",
152 => "delete_sale",
153 => "delete_sales_return",
154 => "department",
155 => "designation",
156 => "discounts",
157 => "do_add",
158 => "do_all",
159 => "do_approval_notification",
160 => "do_delete",
161 => "do_edit",
162 => "do_notification",
163 => "do_to_final",
164 => "do_vs_sales_report",
165 => "e_com_map_tax_rate",
166 => "e_com_sync_order",
167 => "e_com_sync_pro",
168 => "e_com_sync_pro_cate",
169 => "edit_discount_pos_screen",
170 => "edit_discount_sale_screen",
171 => "edit_expense",
172 => "edit_po",
173 => "edit_price_pos_screen",
174 => "edit_price_sale_screen",
175 => "edit_purchase_return",
176 => "edit_requisition",
177 => "edit_sale",
178 => "edit_sales_return",
179 => "email",
180 => "email_settings",
181 => "expanse_report",
182 => "expense_category",
183 => "exporters",
184 => "exporters_create",
185 => "exporters_delete",
186 => "exporters_index",
187 => "exporters_update",
188 => "exporters_view",
189 => "feedback_index",
190 => "financial_report",
191 => "g_settings",
192 => "generate_barcode",
193 => "holiday",
194 => "hrm_dashboard",
195 => "import_purchase_order",
196 => "import_purchase_order_create",
197 => "import_purchase_order_delete",
198 => "import_purchase_order_index",
199 => "import_purchase_order_update",
200 => "import_purchase_order_view",
201 => "insurance_companies",
202 => "insurance_companies_create",
203 => "insurance_companies_delete",
204 => "insurance_companies_index",
205 => "insurance_companies_update",
206 => "insurance_companies_view",
207 => "inv_lay",
208 => "inv_sc",
209 => "leave_assign",
210 => "leave_type",
211 => "loans",
212 => "loss_profit_report",
213 => "manuf_report",
214 => "manuf_settings",
215 => "media",
216 => "memo",
217 => "msg",
218 => "notice_board",
219 => "opening_lc",
220 => "opening_lc_create",
221 => "opening_lc_delete",
222 => "opening_lc_index",
223 => "opening_lc_update",
224 => "opening_lc_view",
225 => "openingStock_add",
226 => "ordered_item_report",
227 => "p_settings",
228 => "payroll",
229 => "payroll_payment_report",
230 => "payroll_report",
231 => "po_notification",
232 => "pos_add",
233 => "pos_all",
234 => "pos_delete",
235 => "pos_edit",
236 => "pos_sale_settings",
237 => "price_update_notification",
238 => "print_challan",
239 => "print_invoice",
240 => "print_weight",
241 => "pro_purchase_report",
242 => "pro_sale_report",
243 => "process_add",
244 => "process_delete",
245 => "process_edit",
246 => "process_report",
247 => "process_view",
248 => "product_add",
249 => "product_all",
250 => "product_delete",
251 => "product_edit",
252 => "product_settings",
253 => "production_add",
254 => "production_delete",
255 => "production_edit",
256 => "production_report",
257 => "production_view",
258 => "profit_loss_ac",
259 => "proj_create",
260 => "proj_delete",
261 => "proj_edit",
262 => "proj_view",
263 => "purchase_add",
264 => "purchase_all",
265 => "purchase_delete",
266 => "purchase_edit",
267 => "purchase_payment_create",
268 => "purchase_payment_delete",
269 => "purchase_payment_index",
270 => "purchase_payment_report",
271 => "purchase_payment_update",
272 => "purchase_payment_view",
273 => "purchase_return",
274 => "purchase_sale_report",
275 => "purchase_settings",
276 => "purchase_statements",
277 => "quotation_notification",
278 => "receive_payment_create",
279 => "receive_payment_delete",
280 => "receive_payment_index",
281 => "receive_payment_update",
282 => "receive_payment_view",
283 => "register_close",
284 => "register_view",
285 => "requisition_notification",
286 => "reset",
287 => "ripe_add_invo",
288 => "ripe_delete_invo",
289 => "ripe_edit_invo",
290 => "ripe_jop_sheet_add",
291 => "ripe_jop_sheet_delete",
292 => "ripe_jop_sheet_edit",
293 => "ripe_jop_sheet_status",
294 => "ripe_only_assinged_job_sheet",
295 => "ripe_view_all_job_sheet",
296 => "ripe_view_invo",
297 => "role_add",
298 => "role_delete",
299 => "role_edit",
300 => "role_view",
301 => "sale_draft",
302 => "sale_order_add",
303 => "sale_order_all",
304 => "sale_order_delete",
305 => "sale_order_do_approval",
306 => "sale_order_edit",
307 => "sale_payment_report",
308 => "sale_quotation_delete",
309 => "sale_quotation_edit",
310 => "sale_quotation_list",
311 => "sale_representative_report",
312 => "sale_return_statements",
313 => "sale_settings",
314 => "sale_statements",
315 => "sales_order_notification",
316 => "sales_order_report",
317 => "selling_price_group",
318 => "shift",
319 => "shipment_access",
320 => "sms",
321 => "sms_settings",
322 => "status_update",
323 => "stock_adjustment_report",
324 => "stock_in_out_report",
325 => "stock_issue",
326 => "stock_issue_create",
327 => "stock_issue_delete",
328 => "stock_issue_index",
329 => "stock_issue_update",
330 => "stock_issue_view",
331 => "stock_out_report",
332 => "stock_report",
333 => "superadmin_access_pack_subscrip",
334 => "supplier_add",
335 => "supplier_all",
336 => "supplier_delete",
337 => "supplier_edit",
338 => "supplier_import",
339 => "supplier_report",
340 => "tax",
341 => "tax_report",
342 => "today_recent_price",
343 => "today_summery",
344 => "transfer_bl_bl",
345 => "transfer_bl_wh",
346 => "transfer_wh_to_bl",
347 => "trial_balance",
348 => "units",
349 => "user_add",
350 => "user_delete",
351 => "user_edit",
352 => "user_view",
353 => "variant",
354 => "view_allowance_and_deduction",
355 => "view_expense",
356 => "view_own_sale",
357 => "view_product_cost_is_sale_screed",
358 => "view_purchase_return",
359 => "view_sales",
360 => "view_sales_return",
361 => "warehouse",
362 => "warranties",
363 => "work_space",
364 => "website_link",
365 => "module_page",


];